repositories:
  remote:
    - https://repo1.maven.org/maven2

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.1.1
  javax_javaee: javax:javaee-api:jar:8.0

  guava: com.google.guava:guava:jar:30.1-jre
  guava_failureaccess: com.google.guava:failureaccess:jar:1.0.1
  google_guice: com.google.inject:guice:jar:5.1.0
  asm: org.ow2.asm:asm:jar:9.2 # Required for guice
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice

  testng: org.testng:testng:jar:6.8
  mockito_core: org.mockito:mockito-core:jar:4.5.1
  byte_buddy: net.bytebuddy:byte-buddy:jar:1.12.9
  objenesis: org.objenesis:objenesis:jar:3.2
  hamcrest: org.hamcrest:hamcrest:jar:2.2
  jndikit: org.realityforge.jndikit:jndikit:jar:1.4
  # Lightweight mail server for testing
  greenmail: com.icegreen:greenmail:jar:1.4.0

  h2db: com.h2database:h2:jar:1.3.159

  glassfish_embedded: fish.payara.extras:payara-embedded-all:jar:5.2022.5
  jtds: net.sourceforge.jtds:jtds:jar:1.3.1
