repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/oss

artifacts:
  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
  javax_javaee: javax:javaee-api:jar:7.0

  google_guice: au.com.stocksoftware.com.google.inject:guice:jar:4.1.1-stock
  asm: org.ow2.asm:asm:jar:5.0.3 # Required for guice
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice

  testng: org.testng:testng:jar:6.8
  mockito: org.mockito:mockito-all:jar:1.9.5
  jndikit: org.realityforge.jndikit:jndikit:jar:1.4
  # Lightweight mail server for testing
  greenmail: com.icegreen:greenmail:jar:1.4.0

  h2db: com.h2database:h2:jar:1.3.159

  glassfish_embedded: fish.payara.extras:payara-embedded-all:jar:4.1.1.164
  jtds: net.sourceforge.jtds:jtds:jar:1.3.1
